FROM node:22-bookworm-slim

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci 

COPY . .

RUN npx prisma generate
RUN npm run build

# Remove devDependencies após build
RUN npm prune --production
RUN rm -rf ./src

EXPOSE 8000

CMD ["npm", "run", "start:prod"]